# Generated by Django 3.1.2 on 2020-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmessage',
            name='complaint_date',
            field=models.DateField(auto_now=True),
        ),
    ]
