# Generated by Django 3.1.2 on 2020-11-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('complaint', '0002_complaintmessage_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmessage',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
    ]
