# Generated by Django 3.1.2 on 2020-11-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone_num', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
